language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
  - os: windows

git:
  clone: false

before_script:
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
        export TCACHEDIR=/c/dev1/cppreflect/out;
      else
        export TCACHEDIR=/home/travis/build/cppreflect/out;
      fi

cache:
    directories:
    - $TCACHEDIR

script: 
    # Fail on first failure
    - set -e
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then mkdir /c/dev1 && cd /c/dev1; fi
    - git clone https://github.com/$TRAVIS_REPO_SLUG.git test_travis_ci && cd test_travis_ci
    - python build.py

notifications:
  email: false
