language: cpp
dist: bionic

matrix:
  include:
  - os: linux
    env: BUILD_TYPE=Release
         BUILD_DIR=/home/travis/build

  - os: linux
    env: BUILD_TYPE=Debug
         BUILD_DIR=/home/travis/build

  - os: windows
    env: BUILD_TYPE=Release
         BUILD_DIR=/c/dev1

  - os: windows
    env: BUILD_TYPE=Debug
         BUILD_DIR=/c/dev1

git:
  clone: false

cache:
    directories:
    $BUILD_DIR/cppreflect/out

script:
    # Fail on first failure
    - set -e
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; 
      then 
        mkdir -p /c/dev1 ;
        cd /c/dev1 ;
      fi
    - git clone https://github.com/$TRAVIS_REPO_SLUG.git test_travis_ci && cd test_travis_ci
    #- if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
    #    export PATH="/c/Python27:/c/Python27/Scripts:$PATH";
    #    choco install python2; 
    #  fi
    - python build.py -buildtype $BUILD_TYPE

notifications:
  email: false
