language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
  - os: windows

git:
  clone: false

cache:
    directories:
    - /c/dev1/cppreflect/out

script: 
    # Fail on first failure
    - set -e
    - sudo mkdir -p /c/dev1 && cd /c/dev1
    - git clone https://github.com/$TRAVIS_REPO_SLUG.git test_travis_ci && cd test_travis_ci
    - python build.py

notifications:
  email: false
