language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
  - os: windows

script:
- python build.py

before_script: 
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then mkdir /c/dev1 && cd /c/dev1; fi

before_install:
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then mkdir /c/dev1 && cd /c/dev1; fi

notifications:
  email: false
