language: cpp
dist: bionic

matrix:
  include:
  - os: linux
    env: BUILD_TYPE=Release BUILD_DIR=/home/travis/build
    python: 3.7

  - os: linux
    env: BUILD_TYPE=Debug BUILD_DIR=/home/travis/build
    python: 3.7

  - os: windows
    env: BUILD_TYPE=Release BUILD_DIR=/c/dev1

  - os: windows
    env: BUILD_TYPE=Debug BUILD_DIR=/c/dev1

git:
  clone: false

cache:
    directories:
    - $BUILD_DIR/out

script:
    # Fail on first failure
    - set -e
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; 
      then 
        mkdir -p /c/dev1 ;
        cd /c/dev1 ;
      fi
    - git clone https://github.com/$TRAVIS_REPO_SLUG.git test_travis_ci && cd test_travis_ci
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
        choco install python3;
        choco install ninja;
        export PATH="/c/Python37:/c/Python37/Scripts:$PATH";
        pip install psutil;
        travis_wait cmd //c python build.py -buildtype $BUILD_TYPE;
      else
        sudo apt-get install -y python3-pip python3-setuptools python-dev ninja-build;
        pip3 install wheel;
        pip3 install psutil;
        python3 build.py -buildtype $BUILD_TYPE;
      fi

notifications:
  email: false
