language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
  - os: windows

git:
  clone: false

cache:
    directories:
    - /c/dev1/cppreflect/out

before_script:
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; 
      then mkdir -p /c/dev1 && cd /c/dev1 ;
      else sudo mkdir -p /c/dev1 && sudo chown -R $USER:$USER /c/dev1 && cd /c/dev1;
      fi

script: 
    # Fail on first failure
    - set -e
    - git clone https://github.com/$TRAVIS_REPO_SLUG.git test_travis_ci && cd test_travis_ci
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
        export PATH="/c/Python27:/c/Python27/Scripts:$PATH";
        choco install python2; 
      fi
    - python build.py

notifications:
  email: false
