language: cpp
dist: bionic

matrix:
  include:
  - os: linux
    env: BUILD_TYPE=Release

  - os: linux
    env: BUILD_TYPE=Debug

  - os: windows
    env: BUILD_TYPE=Release

  - os: windows
    env: BUILD_TYPE=Debug

git:
  clone: false

cache:
    directories:
    # Windows
    - /c/dev1/cppreflect/out
    # Linux
    - /home/travis/build/cppreflect/out

script:
    # Fail on first failure
    - set -e
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; 
      then 
        mkdir -p /c/dev1 ;
        cd /c/dev1 ;
      fi
    - git clone https://github.com/$TRAVIS_REPO_SLUG.git test_travis_ci && cd test_travis_ci
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
        export PATH="/c/Python27:/c/Python27/Scripts:$PATH";
        choco install python2; 
      fi
    - python build.py -buildtype $BUILD_TYPE

notifications:
  email: false
